### ISSUE TITLE
add `opacity: 0.7;` to avoid black background on aside

### ISSUE THREAD

**Issue by hardywu** [mgcrea/bootstrap-additions#6]
````css
.aside-backdrop {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 1040;
  background-color: #000000;
  opacity: 0.7;
}
````
